# Generated by Django 3.1.5 on 2021-01-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DZApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='partners',
            field=models.ManyToManyField(blank=True, through='DZApp.Partnership', to='DZApp.Partner'),
        ),
    ]
