# Generated by Django 3.1.5 on 2021-01-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DZApp', '0002_auto_20210105_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='index',
            field=models.IntegerField(default=1, verbose_name='Индекс'),
        ),
    ]
