# Generated by Django 3.1.5 on 2021-01-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DZApp', '0003_tables_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('partners', models.ManyToManyField(blank=True, to='DZApp.Partner')),
            ],
        ),
    ]
