# Generated by Django 3.1.5 on 2021-01-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DZApp', '0004_testprovider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waybill',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='waybill',
            old_name='provider_id',
            new_name='provider',
        ),
    ]
