# Generated by Django 3.1.5 on 2021-01-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DZApp', '0005_auto_20210109_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='partners',
            field=models.ManyToManyField(blank=True, to='DZApp.Partner'),
        ),
    ]
