# Generated by Django 3.1.5 on 2021-01-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DZApp', '0005_auto_20210109_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='description',
            field=models.CharField(default='', max_length=300, verbose_name='Описание'),
        ),
    ]
